app_api_gesco_category_list_products:
    path: /gesco/categories/products/{code}/{locale}
    defaults: { _controller: app_api.controller.gesco.category:listProductsAction, _format: json, locale: fr_FR }
    methods: [GET]
