app_api_gesco_dependent_attribute_get_all:
    path: /gesco/reference-data/{customEntityName}
    defaults:
        _controller: pim_custom_entity.controller:executeAction
        actionType: rest_getall
    methods: [GET]

app_api_gesco_dependent_attribute_get_by_attribute_and_option:
    path: /gesco/reference-data/dependentattribute/{attributeCode}/{optionCode}
    defaults:
        _controller: app_api.controller.gesco.dependent_attribute:getByAttributeAndOptionAction
    methods: [GET]
