app_api_gesco_product_model_get:
    path: /gesco/product/models/{code}/{locale}
    defaults: { _controller: app_api.controller.gesco.product_model:getAction, _format: json, locale: fr_FR }
    methods: [GET]
