extensions:
    pim-dependentattribute-edit-form:
        module: pim/form/common/edit-form
#        aclResourceId: app_custom_entity_dependentattribute_edit

    pim-dependentattribute-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-dependentattribute-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: app_custom_entity-menu-reference_data-item-dependentattribute

    pim-dependentattribute-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-dependentattribute-edit-form
        position: 1000

    pim-dependentattribute-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-dependentattribute-edit-form
        targetZone: content
        position: 100

    pim-dependentattribute-edit-form-label:
        module: custom_entity/form/common/label
        parent: pim-dependentattribute-edit-form
        targetZone: title
        position: 100

    pim-dependentattribute-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-dependentattribute-edit-form
        targetZone: buttons
        position: 50

    pim-dependentattribute-edit-form-delete:
        module: custom_entity/form/common/delete
        parent: pim-dependentattribute-edit-form-secondary-actions
        targetZone: secondary-actions
        position: 100
        config:
            route: pim_customentity_rest_delete
            routeParams:
                customEntityName: dependentattribute
            trans:
                title: app_custom_entity.message.confirmation.remove.dependentattribute
                container: pim_enrich.confirmation.delete_item
                success: pim_custom_entity.message.confirmation.removed
                fail: pim_custom_entity.error.removing
            redirect: pim_customentity_index

    pim-dependentattribute-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-dependentattribute-edit-form
        targetZone: buttons
        position: 120

    pim-dependentattribute-edit-form-state:
        module: pim/form/common/state
        parent: pim-dependentattribute-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-dependentattribute-edit-form-save:
        module: custom_entity/form/common/save-form
        parent: pim-dependentattribute-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: pim_enrich.entity.attribute.info.update_successful
            updateFailureMessage: pim_enrich.entity.attribute.info.update_failed
            notReadyMessage: pim_enrich.entity.attribute.info.field_not_ready
            url: pim_customentity_rest_edit
            route_params:
                customEntityName: dependentattribute
            redirectAfter: pim_customentity_rest_get
            excludedProperties: []

    pim-dependentattribute-edit-form-properties-tab:
        module: pim/common/tab
        parent: pim-dependentattribute-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: 'pim_custom_entity.form.tab.properties.title'

    pim-dependentattribute-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-dependentattribute-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-dependentattribute-edit-form-state:
        module: pim/form/common/state
        parent: pim-dependentattribute-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-dependentattribute-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-dependentattribute-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-dependentattribute-edit-form-properties-common:
        module: pim/common/simple-view
        parent: pim-dependentattribute-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.common
                dropZone: content

    pim-dependentattribute-edit-form-properties-code:
        module: pim/form/common/fields/text
        parent: pim-dependentattribute-edit-form-properties-common
        targetZone: content
        position: 10
        config:
            fieldName: code
            identifier: code
            label: app_custom_entity.dependentattribute.field.label.code
            required: true
            readOnly: true

    ppim-dependentattribute-edit-form-properties-attribute-code:
        module: pim/form/common/fields/text
        parent: pim-dependentattribute-edit-form-properties-common
        targetZone: content
        position: 20
        config:
            fieldName: attributeCode
            identifier: attributeCode
            label: app_custom_entity.dependentattribute.field.label.attribute_code
            required: true
            readOnly: false

    pim-dependentattribute-edit-form-properties-option-code:
        module: pim/form/common/fields/text
        parent: pim-dependentattribute-edit-form-properties-common
        targetZone: content
        position: 30
        config:
            fieldName: optionCode
            label: app_custom_entity.dependentattribute.field.label.option_code
            required: true
            readOnly: false

    pim-dependentattribute-edit-form-properties-dependent-attribute-code:
        module: pim/form/common/fields/text
        parent: pim-dependentattribute-edit-form-properties-common
        targetZone: content
        position: 40
        config:
            fieldName: dependentAttributeCode
            label: app_custom_entity.dependentattribute.field.label.dependent_attribute_code
            required: true
            readOnly: false

    pim-dependentattribute-edit-form-properties-dependent-option-code:
        module: pim/form/common/fields/text
        parent: pim-dependentattribute-edit-form-properties-common
        targetZone: content
        position: 50
        config:
            fieldName: dependentOptionCode
            label: app_custom_entity.dependentattribute.field.label.dependent_option_code
            required: true
            readOnly: false
