extensions:
    pim-dependentattribute-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    pim-dependentattribute-index-grid-container:
        module: pim/common/simple-view
        parent: pim-dependentattribute-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-dependentattribute-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-dependentattribute-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-dependentattribute-index-grid-title:
        module: pim/common/grid-title
        parent: pim-dependentattribute-index
        targetZone: title
        config:
            title: app_custom_entity.dependentattribute.index_title

    pim-dependentattribute-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-dependentattribute-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: app_custom_entity-menu-reference_data-item-dependentattribute

    pim-dependentattribute-index-grid-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-dependentattribute-index-grid-container
        targetZone: filters

    pim-dependentattribute-index-grid-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-dependentattribute-index-grid-container
        targetZone: filters

    pim-dependentattribute-index-mass-actions:
        module: pim/grid/mass-actions
        parent: pim-dependentattribute-index
        targetZone: bottom-panel
        config:
            label: app_custom_entity.dependentattribute.selected

    pim-dependentattribute-index-actions-panel:
        module: oro/datagrid/actions-panel
        parent: pim-dependentattribute-index-mass-actions
        targetZone: actions-panel

    pim-dependentattribute-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-dependentattribute-index-grid-container
        targetZone: toolbar
        config:
            gridName: dependentattribute

    pim-dependentattribute-index-grid:
        module: pim/form/common/index/grid
        parent: pim-dependentattribute-index
        targetZone: content
        position: 1000
        config:
            alias: dependentattribute

    pim-dependentattribute-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-dependentattribute-index
        targetZone: buttons
        aclResourceId: app_custom_entity_dependentattribute_create
        config:
           title:     pim_custom_entity.button.create
           modalForm: pim-dependentattribute-create-modal