services:
    app_api.controller.gesco.category:
        class:  App\ApiBundle\Controller\Gesco\CategoryController

    app_api.controller.gesco.product:
        class:  App\ApiBundle\Controller\Gesco\ProductController

    app_api.controller.gesco.product_model:
        class:  App\ApiBundle\Controller\Gesco\ProductModelController

    app_api.controller.gesco.dependent_attribute:
        class:  App\ApiBundle\Controller\Gesco\DependentAttributeController
