services:
    # Gesco product
    app_api.normalizer.gesco.product.associations:
        class: App\ApiBundle\Normalizer\Gesco\Product\AssociationsNormalizer
        calls:
            - [ setNormalizer, ['@pim_serializer'] ]

    app_api.normalizer.gesco.product.metric:
        class: App\ApiBundle\Normalizer\Gesco\Product\MetricNormalizer
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    app_api.normalizer.gesco.product.price:
        class: App\ApiBundle\Normalizer\Gesco\Product\PriceNormalizer
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    app_api.normalizer.gesco.product.product_value:
        class: App\ApiBundle\Normalizer\Gesco\Product\ProductValueNormalizer
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    app_api.normalizer.gesco.product.product_values:
        class: App\ApiBundle\Normalizer\Gesco\Product\ProductValuesNormalizer
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    app_api.normalizer.gesco.product.properties:
        class: App\ApiBundle\Normalizer\Gesco\Product\PropertiesNormalizer
        arguments:
            - '@pim_catalog.filter.chained'
            - '@app_api.normalizer.gesco.family'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    # Gesco
    app_api.normalizer.gesco.category:
        class: App\ApiBundle\Normalizer\Gesco\CategoryNormalizer
        arguments:
            - '@app_api.repository.product'
            - '@app_api.repository.product_model'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    app_api.normalizer.gesco.family:
        class: App\ApiBundle\Normalizer\Gesco\FamilyNormalizer

    app_api.normalizer.gesco.datetime:
        class: App\ApiBundle\Normalizer\Gesco\DateTimeNormalizer
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    app_api.normalizer.gesco.product_model:
        class: App\ApiBundle\Normalizer\Gesco\ProductModelNormalizer
        arguments:
            - '@app_api.normalizer.gesco.family'

    app_api.normalizer.gesco.product:
        class: App\ApiBundle\Normalizer\Gesco\ProductNormalizer
        arguments:
            - '@app_api.normalizer.gesco.product.properties'
            - '@app_api.normalizer.gesco.product.associations'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
